"""Export current command defaults as editable Hydra configuration examples."""

import shlex
from pathlib import Path

from hydra import compose, initialize_config_module
from hydra_zen import store
from loguru import logger
from omegaconf import OmegaConf

from clearml_yolo.configs import NATIVE_BLOCKS

COMMAND_OF_CONFIG = {
    "pipeline": "cy",
    "train": "cy-train",
    "predict": "cy-predict",
    "val": "cy-val",
    "metrics": "cy-metrics",
    "report": "cy-report",
    "compare": "cy-compare",
    "ground_truth": "cy-ground-truth",
}


def _header(config_name: str, command: str, directory: Path) -> str:
    lines = [
        "# Generated by cy-init-config. Edit this example, then run:",
        (
            f"#   {command} --config-dir {shlex.quote(str(directory.resolve()))} "
            f"--config-name {command}"
        ),
        "# Replace ??? with your required inputs before running.",
        "# Relative input paths are resolved from the working directory.",
        "# Set clearml.project_name, clearml.task_name and clearml.tags for your run.",
    ]
    if config_name == "pipeline":
        lines.append("# Set run_dir to route all pipeline outputs together.")
    if config_name in {"predict", "val"}:
        lines.append("# Set weights to your trained checkpoint (or use ultralytics.model).")
    for parent in NATIVE_BLOCKS.get(config_name, []):
        prefix = f"{parent}." if parent else ""
        lines.extend(
            [
                f"# Native YAML: {prefix}cfg=native.yaml; embedded keys take precedence.",
                (
                    f"# Add native keys: +{prefix}ultralytics.device=cpu; "
                    "omit + to override existing keys."
                ),
            ]
        )
        if config_name == "train" or parent == "train":
            lines.append(
                f"# Training example: +{prefix}ultralytics.model=yolo11n.pt "
                f"+{prefix}ultralytics.data=data.yaml +{prefix}ultralytics.epochs=10"
            )
    return "\n".join(lines) + "\n\n"


def dump_config_tree(directory: str | Path, *, overwrite: bool = False) -> list[Path]:
    """Write one example per pipeline/stage command, preserving existing files by default."""
    target = Path(directory).expanduser()
    paths = [target / f"{command}.yaml" for command in COMMAND_OF_CONFIG.values()]
    # Check every destination before writing any examples, including dangling symlinks.
    for path in paths:
        if path.exists() or path.is_symlink():
            if not overwrite:
                raise FileExistsError(f"{path} already exists. Pass --force to overwrite examples.")
            if path.is_symlink() or not path.is_file():
                raise FileExistsError(f"{path} is not a regular file; choose another directory.")

    store.add_to_hydra_store(overwrite_ok=True)
    contents = []
    with initialize_config_module(config_module="hydra_zen.wrapper", version_base="1.3"):
        for config_name, command in COMMAND_OF_CONFIG.items():
            config = compose(config_name=config_name)
            contents.append(
                _header(config_name, command, target) + OmegaConf.to_yaml(config, resolve=False)
            )

    target.mkdir(parents=True, exist_ok=True)
    for path, content in zip(paths, contents, strict=True):
        # Exclusive creation also protects files created after the initial preflight.
        with path.open("w" if overwrite else "x", encoding="utf-8") as stream:
            stream.write(content)
        logger.info("Wrote {}", path)
    return paths
