"""Write the project's defaults out as an editable Hydra config folder.

Every setting lives in the hydra-zen store, which is Python: readable only by running
the app with ``--cfg job``, and not something a user can keep under version control
next to their data. This dumps one complete config per console script into a directory
that ``--config-dir`` then reads back.

The dumped files are deliberately *not* named after the store entries they came from.
Hydra's automatic schema matching — where a YAML file inherits the structured config of
the same name — was removed after 1.1, and for the entries carrying a defaults list
(``pipeline`` and ``report``) a same-named file is a hard error rather than a warning.
Naming each file after its command sidesteps the collision entirely and reads better on
the command line.

The ultralytics parameter sets are the one thing not flattened into the command's file.
They are copied out of the package byte for byte, into an ``ultralytics/`` subdirectory
the command's file then names in its defaults list. Rendering them through
``OmegaConf.to_yaml`` like everything else would drop every comment, and the comments are
what make a hundred and fifteen parameters legible.
"""

from __future__ import annotations

from importlib.resources import files
from pathlib import Path
from typing import Any

from hydra import compose, initialize_config_module
from hydra_zen import store
from loguru import logger
from omegaconf import OmegaConf

import clearml_yolo.configs  # noqa: F401  registers every config

# Config name in the store -> file name in the dumped folder, which is the command that
# reads it. `cy` composes all four stages; the rest are the standalone apps.
COMMAND_OF_CONFIG = {
    "pipeline": "cy",
    "train": "cy-train",
    "predict": "cy-predict",
    "metrics": "cy-metrics",
    "report": "cy-report",
    "compare": "cy-compare",
    "ground_truth": "cy-ground-truth",
}

ULTRALYTICS_GROUP_DIR = "ultralytics"

# Where each command's ultralytics block sits in its composed config, and which file in
# the group directory fills it. A command absent from here has no such block.
ULTRALYTICS_BLOCKS: dict[str, dict[str, str]] = {
    "cy-train": {"ultralytics": "train"},
    "cy-predict": {"ultralytics": "predict"},
    "cy": {"train.ultralytics": "train", "predict.ultralytics": "predict"},
}

HEADER = """# Generated by `cy-init-config`. Edit freely, then run:
#     uv run {command} --config-dir {directory} --config-name {name}
"""

# Only in the pipeline's own file: it is the only one composed of stage blocks, and a
# reader who takes a short list for the whole of it reaches for a stage's own key instead —
# `predict.output=`, which is now the run's to decide and does not compose at all.
SHARED_VALUES_NOTE = """#
# The values more than one stage needs — clearml, auto_gpu, ground_truth, splits, weights,
# run_id, run_dir — are named once at the top level here and handed to each stage by the
# run. A stage block holds only what that stage alone decides, so a whole run is
# redirected with `run_dir=<somewhere>` and never with a path inside a stage block.
"""

# Only for the commands that mount such a block. The rest take no ultralytics parameters at
# all, and Hydra refuses an override naming a group a config never mounted.
ULTRALYTICS_NOTE = """#
# Every ultralytics parameter lives in {group}/, one file per stage, each listing the
# whole of ultralytics' configuration with its own documentation. Edit those in place, or
# copy one and select the copy by name:
{overrides}
"""


def _composed(config_name: str) -> dict[str, Any]:
    """Compose one app's config exactly as its CLI would, leaving interpolations intact.

    Returned as a plain container rather than a ``DictConfig``: the composed node is
    backed by a generated dataclass, which refuses to have a key deleted, and lifting the
    ultralytics blocks back out is a deletion.
    """
    with initialize_config_module(config_module="hydra_zen.wrapper", version_base="1.3"):
        config = compose(config_name=config_name)
    # resolve=False so a standalone config that does carry an interpolation keeps it, and
    # so dumping never depends on a value being resolvable at dump time.
    container: dict[str, Any] = OmegaConf.to_container(config, resolve=False)  # type: ignore[assignment]
    return container


def _lift_ultralytics(config: dict[str, Any], blocks: dict[str, str]) -> str:
    """Remove each ultralytics block from ``config`` and return the defaults list naming it.

    The blocks are files of their own in the dumped folder, so leaving the composed values
    inline as well would put the same hundred and fifteen parameters in two places, where
    editing either one leaves the other stale.

    The group is named absolutely, with a leading slash, so one ``ultralytics/`` directory
    answers both ``cy-train`` and the ``train`` block inside ``cy``.
    """
    if not blocks:
        return ""
    for dotted in blocks:
        parent, _, leaf = dotted.rpartition(".")
        node = config
        for step in parent.split(".") if parent else []:
            node = node[step]
        del node[leaf]
    entries = "\n".join(
        f"  - /{ULTRALYTICS_GROUP_DIR}@{dotted}: {name}" for dotted, name in blocks.items()
    )
    return f"defaults:\n  - _self_\n{entries}\n\n"


def _header(command: str, target: Path) -> str:
    """What this command's file says about itself, and nothing another command's file says.

    The paragraphs are assembled per command rather than written out once, because both of
    them are false somewhere: the shared top-level values exist only in the pipeline's file,
    and the ultralytics group is mounted at a different key in every command that has one —
    at the top level for a standalone app, once per stage inside `cy`. An override printed
    against the wrong key is refused by Hydra outright rather than ignored, so a header that
    printed one spelling everywhere sent most of its readers to a composition error.
    """
    text = HEADER.format(command=command, directory=target, name=command)
    if command == COMMAND_OF_CONFIG["pipeline"]:
        text += SHARED_VALUES_NOTE
    blocks = ULTRALYTICS_BLOCKS.get(command, {})
    if blocks:
        overrides = "\n".join(
            f"#     {command} {ULTRALYTICS_GROUP_DIR}"
            f"{'' if dotted == ULTRALYTICS_GROUP_DIR else f'@{dotted}'}=<file-stem>"
            for dotted in blocks
        )
        text += ULTRALYTICS_NOTE.format(group=ULTRALYTICS_GROUP_DIR, overrides=overrides)
    return text


def _dump_group(target: Path, *, overwrite: bool) -> list[Path]:
    """Copy the packaged ultralytics parameter files out, comments and all."""
    source = files("clearml_yolo.conf").joinpath(ULTRALYTICS_GROUP_DIR)
    directory = target / ULTRALYTICS_GROUP_DIR
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for entry in sorted(source.iterdir(), key=lambda item: item.name):
        if not entry.name.endswith(".yaml"):
            continue
        path = directory / entry.name
        _refuse_existing(path, overwrite=overwrite)
        path.write_text(entry.read_text(encoding="utf-8"), encoding="utf-8")
        written.append(path)
        logger.info("Wrote {}", path)
    return written


def _refuse_existing(path: Path, *, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(
            f"{path} already exists. Pass --force to overwrite it, or dump into an "
            "empty directory to keep your edits."
        )


def dump_config_tree(directory: str | Path, *, overwrite: bool = False) -> list[Path]:
    """Write one complete, editable config file per console script into ``directory``."""
    store.add_to_hydra_store(overwrite_ok=True)
    target = Path(directory).expanduser()
    target.mkdir(parents=True, exist_ok=True)

    registered = {entry["name"] for entry in store if entry["group"] is None}
    written = _dump_group(target, overwrite=overwrite)
    for config_name, command in COMMAND_OF_CONFIG.items():
        if config_name not in registered:
            logger.warning("No config registered under {!r}; skipping it", config_name)
            continue
        path = target / f"{command}.yaml"
        _refuse_existing(path, overwrite=overwrite)
        config = _composed(config_name)
        defaults = _lift_ultralytics(config, ULTRALYTICS_BLOCKS.get(command, {}))
        body = str(OmegaConf.to_yaml(OmegaConf.create(config), resolve=False))
        path.write_text(f"{_header(command, target)}\n{defaults}{body}", encoding="utf-8")
        written.append(path)
        logger.info("Wrote {}", path)

    logger.info("Wrote {} config file(s) to {}", len(written), target)
    return written
